<concat>
  <concatItem>
    <literal>
      <string>
        <content>A</content>
        <url>/functions01.php</url>
        <line>2</line>
      </string>
    </literal>
  </concatItem>
  <concatItem>
    <literal>
      <string>
        <content>pre</content>
        <url>/functions01.php</url>
        <line>5</line>
      </string>
    </literal>
  </concatItem>
  <concatItem>
    <literal>
      <string>
        <content>B2D</content>
        <url>/functions01.php</url>
        <line>7</line>
      </string>
    </literal>
  </concatItem>
  <concatItem>
    <literal>
      <string>
        <content>post</content>
        <url>/functions01.php</url>
        <line>11</line>
      </string>
    </literal>
  </concatItem>
  <concatItem>
    <literal>
      <string>
        <content>pre</content>
        <url>/functions01.php</url>
        <line>5</line>
      </string>
    </literal>
  </concatItem>
  <concatItem>
    <select>
      <condition> true &amp;&amp; ($x &gt; 0) </condition>
      <trueNode>
        <literal>
          <string>
            <content>B2D</content>
            <url>/functions01.php</url>
            <line>7</line>
          </string>
        </literal>
      </trueNode>
      <falseNode>
        <literal>
          <string>
            <content>B3</content>
            <url>/functions01.php</url>
            <line>9</line>
          </string>
        </literal>
      </falseNode>
    </select>
  </concatItem>
  <concatItem>
    <literal>
      <string>
        <content>post</content>
        <url>/functions01.php</url>
        <line>11</line>
      </string>
    </literal>
  </concatItem>
  <concatItem>
    <literal>
      <string>
        <content>Z</content>
        <url>/functions01.php</url>
        <line>15</line>
      </string>
    </literal>
  </concatItem>
</concat>