<concat>
<concatItem>
<literal>
<string>
<content>A</content>
<url>file:/home/stefan/git/oak/edu.cmu.cs.oak/bin/testScripts/ifStatement01.php</url>
<line>2</line>
</string>
</literal>
</concatItem>
<concatItem>
<select>
<condition> true &amp;&amp; ($i &lt; &quot;g&quot;) </condition>
<trueNode>
<concat>
<concatItem>
<literal>
<string>
<content>A1</content>
<url>file:/home/stefan/git/oak/edu.cmu.cs.oak/bin/testScripts/ifStatement01.php</url>
<line>5</line>
</string>
</literal>
</concatItem>
<concatItem>
<literal>
<string>
<content>B</content>
<url>file:/home/stefan/git/oak/edu.cmu.cs.oak/bin/testScripts/ifStatement01.php</url>
<line>6</line>
</string>
</literal>
</concatItem>
</concat>
</trueNode>
<falseNode>
<concat>
<concatItem>
<literal>
<string>
<content>A2</content>
<url>file:/home/stefan/git/oak/edu.cmu.cs.oak/bin/testScripts/ifStatement01.php</url>
<line>8</line>
</string>
</literal>
</concatItem>
<concatItem>
<literal>
<string>
<content>C</content>
<url>file:/home/stefan/git/oak/edu.cmu.cs.oak/bin/testScripts/ifStatement01.php</url>
<line>9</line>
</string>
</literal>
</concatItem>
</concat>
</falseNode>
</select>
</concatItem>
<concatItem>
<literal>
<string>
<content>D</content>
<url>file:/home/stefan/git/oak/edu.cmu.cs.oak/bin/testScripts/ifStatement01.php</url>
<line>11</line>
</string>
</literal>
</concatItem>
</concat>